version: '3.8'

services:
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - rabbitmq

  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  data:
